"""init

Revision ID: 118243b0e1ab
Revises: 
Create Date: 2026-05-25 23:19:55.919278

"""
from alembic import op
import sqlalchemy as sa


revision = '118243b0e1ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='accounts'
    )
    op.create_index(op.f('ix_accounts_users_email'), 'users', ['email'], unique=True, schema='accounts')
    op.create_index(op.f('ix_accounts_users_username'), 'users', ['username'], unique=True, schema='accounts')
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_groups_admin_user_id'), 'groups', ['admin_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_groups_key_hash'), 'groups', ['key_hash'], unique=True, schema='app')
    op.create_index(op.f('ix_app_groups_slug'), 'groups', ['slug'], unique=True, schema='app')
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('join_request_created', 'join_request_accepted', 'join_request_rejected', 'task_assigned', 'subtask_assigned', 'member_removed', 'group_deleted', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='app')
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(owner_user_id IS NOT NULL) <> (group_id IS NOT NULL)', name='ck_category_scope_exclusive'),
    sa.ForeignKeyConstraint(['group_id'], ['app.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_categories_group_id'), 'categories', ['group_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_categories_owner_user_id'), 'categories', ['owner_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_categories_slug'), 'categories', ['slug'], unique=True, schema='app')
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='group_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['app.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member'),
    schema='app'
    )
    op.create_index(op.f('ix_app_group_members_group_id'), 'group_members', ['group_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_group_members_user_id'), 'group_members', ['user_id'], unique=False, schema='app')
    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'expired', name='join_request_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['app.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_join_requests_group_id'), 'join_requests', ['group_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_join_requests_slug'), 'join_requests', ['slug'], unique=True, schema='app')
    op.create_index(op.f('ix_app_join_requests_user_id'), 'join_requests', ['user_id'], unique=False, schema='app')
    op.create_index('ix_join_request_pending', 'join_requests', ['group_id', 'user_id', 'status'], unique=False, schema='app')
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(owner_user_id IS NOT NULL) <> (group_id IS NOT NULL)', name='ck_tag_scope_exclusive'),
    sa.ForeignKeyConstraint(['group_id'], ['app.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'group_id', name='uq_tag_name_group'),
    sa.UniqueConstraint('name', 'owner_user_id', name='uq_tag_name_owner'),
    schema='app'
    )
    op.create_index(op.f('ix_app_tags_group_id'), 'tags', ['group_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_tags_owner_user_id'), 'tags', ['owner_user_id'], unique=False, schema='app')
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'done', 'archived', name='task_status'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(owner_user_id IS NOT NULL) <> (group_id IS NOT NULL)', name='ck_task_scope_exclusive'),
    sa.CheckConstraint('start_date <= due_date', name='ck_task_dates'),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['accounts.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['app.categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['app.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_tasks_assignee_user_id'), 'tasks', ['assignee_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_tasks_category_id'), 'tasks', ['category_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_tasks_creator_user_id'), 'tasks', ['creator_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_tasks_group_id'), 'tasks', ['group_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_tasks_owner_user_id'), 'tasks', ['owner_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_tasks_slug'), 'tasks', ['slug'], unique=True, schema='app')
    op.create_table('subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'done', 'archived', name='task_status'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.UUID(), nullable=False),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_date <= due_date', name='ck_subtask_dates'),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['accounts.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['app.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_subtasks_assignee_user_id'), 'subtasks', ['assignee_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_subtasks_creator_user_id'), 'subtasks', ['creator_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_subtasks_slug'), 'subtasks', ['slug'], unique=True, schema='app')
    op.create_index(op.f('ix_app_subtasks_task_id'), 'subtasks', ['task_id'], unique=False, schema='app')
    op.create_table('task_tags',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['app.tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['app.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_tags', schema='app')
    op.drop_index(op.f('ix_app_subtasks_task_id'), table_name='subtasks', schema='app')
    op.drop_index(op.f('ix_app_subtasks_slug'), table_name='subtasks', schema='app')
    op.drop_index(op.f('ix_app_subtasks_creator_user_id'), table_name='subtasks', schema='app')
    op.drop_index(op.f('ix_app_subtasks_assignee_user_id'), table_name='subtasks', schema='app')
    op.drop_table('subtasks', schema='app')
    op.drop_index(op.f('ix_app_tasks_slug'), table_name='tasks', schema='app')
    op.drop_index(op.f('ix_app_tasks_owner_user_id'), table_name='tasks', schema='app')
    op.drop_index(op.f('ix_app_tasks_group_id'), table_name='tasks', schema='app')
    op.drop_index(op.f('ix_app_tasks_creator_user_id'), table_name='tasks', schema='app')
    op.drop_index(op.f('ix_app_tasks_category_id'), table_name='tasks', schema='app')
    op.drop_index(op.f('ix_app_tasks_assignee_user_id'), table_name='tasks', schema='app')
    op.drop_table('tasks', schema='app')
    op.drop_index(op.f('ix_app_tags_owner_user_id'), table_name='tags', schema='app')
    op.drop_index(op.f('ix_app_tags_group_id'), table_name='tags', schema='app')
    op.drop_table('tags', schema='app')
    op.drop_index('ix_join_request_pending', table_name='join_requests', schema='app')
    op.drop_index(op.f('ix_app_join_requests_user_id'), table_name='join_requests', schema='app')
    op.drop_index(op.f('ix_app_join_requests_slug'), table_name='join_requests', schema='app')
    op.drop_index(op.f('ix_app_join_requests_group_id'), table_name='join_requests', schema='app')
    op.drop_table('join_requests', schema='app')
    op.drop_index(op.f('ix_app_group_members_user_id'), table_name='group_members', schema='app')
    op.drop_index(op.f('ix_app_group_members_group_id'), table_name='group_members', schema='app')
    op.drop_table('group_members', schema='app')
    op.drop_index(op.f('ix_app_categories_slug'), table_name='categories', schema='app')
    op.drop_index(op.f('ix_app_categories_owner_user_id'), table_name='categories', schema='app')
    op.drop_index(op.f('ix_app_categories_group_id'), table_name='categories', schema='app')
    op.drop_table('categories', schema='app')
    op.drop_index(op.f('ix_app_notifications_user_id'), table_name='notifications', schema='app')
    op.drop_table('notifications', schema='app')
    op.drop_index(op.f('ix_app_groups_slug'), table_name='groups', schema='app')
    op.drop_index(op.f('ix_app_groups_key_hash'), table_name='groups', schema='app')
    op.drop_index(op.f('ix_app_groups_admin_user_id'), table_name='groups', schema='app')
    op.drop_table('groups', schema='app')
    op.drop_index(op.f('ix_accounts_users_username'), table_name='users', schema='accounts')
    op.drop_index(op.f('ix_accounts_users_email'), table_name='users', schema='accounts')
    op.drop_table('users', schema='accounts')
    # ### end Alembic commands ###
