"""add activity log, task position and state timestamps

Revision ID: 12de58e47ee3
Revises: 7f23e4c53a3e
Create Date: 2026-06-30 21:08:06.302428

"""
from alembic import op
import sqlalchemy as sa


revision = '12de58e47ee3'
down_revision = '7f23e4c53a3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('type', sa.Enum('created', 'status_changed', 'delivered', 'reopened', 'category_moved', 'assignee_changed', 'urgent_changed', 'dates_changed', name='activity_type'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('subtask_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(task_id IS NOT NULL) <> (subtask_id IS NOT NULL)', name='ck_activity_target_exclusive'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtask_id'], ['app.subtasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['app.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_activities_actor_user_id'), 'activities', ['actor_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_activities_slug'), 'activities', ['slug'], unique=True, schema='app')
    op.create_index(op.f('ix_app_activities_subtask_id'), 'activities', ['subtask_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_activities_task_id'), 'activities', ['task_id'], unique=False, schema='app')
    op.add_column('subtasks', sa.Column('status_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='app')
    op.add_column('subtasks', sa.Column('assignee_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='app')
    op.add_column('tasks', sa.Column('position', sa.Float(), server_default='0', nullable=False), schema='app')
    op.add_column('tasks', sa.Column('status_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='app')
    op.add_column('tasks', sa.Column('category_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='app')
    op.add_column('tasks', sa.Column('assignee_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='app')
    op.create_index('ix_task_category_position', 'tasks', ['category_id', 'position'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_category_position', table_name='tasks', schema='app')
    op.drop_column('tasks', 'assignee_changed_at', schema='app')
    op.drop_column('tasks', 'category_changed_at', schema='app')
    op.drop_column('tasks', 'status_changed_at', schema='app')
    op.drop_column('tasks', 'position', schema='app')
    op.drop_column('subtasks', 'assignee_changed_at', schema='app')
    op.drop_column('subtasks', 'status_changed_at', schema='app')
    op.drop_index(op.f('ix_app_activities_task_id'), table_name='activities', schema='app')
    op.drop_index(op.f('ix_app_activities_subtask_id'), table_name='activities', schema='app')
    op.drop_index(op.f('ix_app_activities_slug'), table_name='activities', schema='app')
    op.drop_index(op.f('ix_app_activities_actor_user_id'), table_name='activities', schema='app')
    op.drop_table('activities', schema='app')
    # ### end Alembic commands ###
