"""init

Revision ID: 4a8f277627e7
Revises: 
Create Date: 2026-05-23 17:42:12.727512

"""
from alembic import op
import sqlalchemy as sa


revision = '4a8f277627e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=16), nullable=False), schema='app')
    op.create_index(op.f('ix_app_categories_slug'), 'categories', ['slug'], unique=True, schema='app')
    op.add_column('groups', sa.Column('slug', sa.String(length=16), nullable=False), schema='app')
    op.create_index(op.f('ix_app_groups_slug'), 'groups', ['slug'], unique=True, schema='app')
    op.add_column('join_requests', sa.Column('slug', sa.String(length=16), nullable=False), schema='app')
    op.create_index(op.f('ix_app_join_requests_slug'), 'join_requests', ['slug'], unique=True, schema='app')
    op.add_column('subtasks', sa.Column('slug', sa.String(length=16), nullable=False), schema='app')
    op.create_index(op.f('ix_app_subtasks_slug'), 'subtasks', ['slug'], unique=True, schema='app')
    op.add_column('tasks', sa.Column('slug', sa.String(length=16), nullable=False), schema='app')
    op.create_index(op.f('ix_app_tasks_slug'), 'tasks', ['slug'], unique=True, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_tasks_slug'), table_name='tasks', schema='app')
    op.drop_column('tasks', 'slug', schema='app')
    op.drop_index(op.f('ix_app_subtasks_slug'), table_name='subtasks', schema='app')
    op.drop_column('subtasks', 'slug', schema='app')
    op.drop_index(op.f('ix_app_join_requests_slug'), table_name='join_requests', schema='app')
    op.drop_column('join_requests', 'slug', schema='app')
    op.drop_index(op.f('ix_app_groups_slug'), table_name='groups', schema='app')
    op.drop_column('groups', 'slug', schema='app')
    op.drop_index(op.f('ix_app_categories_slug'), table_name='categories', schema='app')
    op.drop_column('categories', 'slug', schema='app')
    # ### end Alembic commands ###
