"""add daily habits tracker

Revision ID: 55b7ed9b9f6a
Revises: 20ae144b9949
Create Date: 2026-06-08 23:02:01.861207

"""
from alembic import op
import sqlalchemy as sa


revision = '55b7ed9b9f6a'
down_revision = '20ae144b9949'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('every_day', sa.Boolean(), nullable=False),
    sa.Column('days_mask', sa.SmallInteger(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('days_mask >= 1 AND days_mask <= 127', name='ck_habit_days_mask_range'),
    sa.CheckConstraint('every_day = false OR days_mask = 127', name='ck_habit_every_day_mask'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_habits_owner_user_id'), 'habits', ['owner_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_habits_slug'), 'habits', ['slug'], unique=True, schema='app')
    op.create_table('habit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'done', name='habit_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['app.habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'entry_date', name='uq_habit_entry_date'),
    schema='app'
    )
    op.create_index(op.f('ix_app_habit_entries_habit_id'), 'habit_entries', ['habit_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_habit_entries_habit_id'), table_name='habit_entries', schema='app')
    op.drop_table('habit_entries', schema='app')
    op.drop_index(op.f('ix_app_habits_slug'), table_name='habits', schema='app')
    op.drop_index(op.f('ix_app_habits_owner_user_id'), table_name='habits', schema='app')
    op.drop_table('habits', schema='app')
    # ### end Alembic commands ###
