"""add comments

Revision ID: 7f23e4c53a3e
Revises: 2c1f4f53bbdb
Create Date: 2026-06-29 23:20:53.522657

"""
from alembic import op
import sqlalchemy as sa


revision = '7f23e4c53a3e'
down_revision = '2c1f4f53bbdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('subtask_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(task_id IS NOT NULL) <> (subtask_id IS NOT NULL)', name='ck_comment_target_exclusive'),
    sa.ForeignKeyConstraint(['author_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtask_id'], ['app.subtasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['app.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_comments_author_user_id'), 'comments', ['author_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_comments_slug'), 'comments', ['slug'], unique=True, schema='app')
    op.create_index(op.f('ix_app_comments_subtask_id'), 'comments', ['subtask_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_comments_task_id'), 'comments', ['task_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_comments_task_id'), table_name='comments', schema='app')
    op.drop_index(op.f('ix_app_comments_subtask_id'), table_name='comments', schema='app')
    op.drop_index(op.f('ix_app_comments_slug'), table_name='comments', schema='app')
    op.drop_index(op.f('ix_app_comments_author_user_id'), table_name='comments', schema='app')
    op.drop_table('comments', schema='app')
    # ### end Alembic commands ###
