"""add is_urgent flag to tasks and subtasks

Revision ID: a5b74fe9f148
Revises: c058c6555be3
Create Date: 2026-06-29 19:01:16.890195

"""
from alembic import op
import sqlalchemy as sa


revision = 'a5b74fe9f148'
down_revision = 'c058c6555be3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtasks', sa.Column('is_urgent', sa.Boolean(), server_default='false', nullable=False), schema='app')
    op.add_column('tasks', sa.Column('is_urgent', sa.Boolean(), server_default='false', nullable=False), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_urgent', schema='app')
    op.drop_column('subtasks', 'is_urgent', schema='app')
    # ### end Alembic commands ###
