"""add user timezone

Revision ID: affa0a6a8be1
Revises: 55b7ed9b9f6a
Create Date: 2026-06-08 23:10:40.154978

"""
from alembic import op
import sqlalchemy as sa


revision = 'affa0a6a8be1'
down_revision = '55b7ed9b9f6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False), schema='accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone', schema='accounts')
    # ### end Alembic commands ###
