"""remove_refresh_tokens_table

Revision ID: ed5f14870602
Revises: 4a8f277627e7
Create Date: 2026-05-23 21:34:54.593895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ed5f14870602'
down_revision = '4a8f277627e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_refresh_tokens_jti', table_name='refresh_tokens', schema='accounts')
    op.drop_index('ix_accounts_refresh_tokens_user_id', table_name='refresh_tokens', schema='accounts')
    op.drop_index('ix_refresh_tokens_user_active', table_name='refresh_tokens', schema='accounts')
    op.drop_table('refresh_tokens', schema='accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('session_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('session_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('replaced_by_jti', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.users.id'], name='refresh_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pkey'),
    schema='accounts'
    )
    op.create_index('ix_refresh_tokens_user_active', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False, schema='accounts')
    op.create_index('ix_accounts_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False, schema='accounts')
    op.create_index('ix_accounts_refresh_tokens_jti', 'refresh_tokens', ['jti'], unique=True, schema='accounts')
    # ### end Alembic commands ###
